version: '3.8'

services:
  web:
    image: ${REPOSITORY}:${TAG} # These variables will be read from the environment
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:80"
    env_file:
      - .env.production
